version: '3'

services:

  db:
    container_name: db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../data/db:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
      - PMA_ARBITRARY=1
      ports:
      - 8080:80
      volumes:
      - /sessions
      
  httpd:
    container_name: httpd
    image: camptocamp/os-wp-httpd
    volumes:
      - ./srv:/srv
    links:
      - db:db
    environment:
      - WP_ENV=${WP_ENV}
    ports:
      - "80:80"
      - "443:443"

  mgmt:
    container_name: mgmt
    image: camptocamp/os-wp-mgmt
    env_file:
      - .env
    environment:
      - WP_ENV=${WP_ENV}
      - LOGGING_FILE=/srv/${WP_ENV}/logs/jahia2wp.log
    volumes:
      - ./srv:/srv
      - ..:/srv/${WP_ENV}/jahia2wp
    ports:
      - "2222:22"
