# (c) All rights reserved. ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017
---
language: python

python:
- '3.6'

install:
- pip install -r requirements/local.txt

script:
- flake8.sh --max-line-length=120 src
- pytest --cov=./ src
- codecov -t $CODECOV_TOKEN
