# (c) All rights reserved. ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017
---
sudo: required

services:
- docker

language: python

python:
- '3.6'

before_install:
- docker pull camptocamp/os-wp-httpd
- docker pull camptocamp/os-wp-mgmt

install:
- cd local
- make up
- docker exec mgmt make -C /srv/$WP_ENV/jahia2wp/local bootstrap-mgmt

script:
- docker exec mgmt make -C /srv/$WP_ENV/jahia2wp test-travis
