# (c) All rights reserved. ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017
---
sudo: required

services:
- docker

language: python

python:
- 3.6

before_install:
- docker pull camptocamp/os-wp-httpd
- docker pull camptocamp/os-wp-mgmt
- cp local/.env.sample local/.env

install:
- make -C local up
- docker exec mgmt make -C /srv/$WP_ENV/jahia2wp/local bootstrap-mgmt

script:
- docker exec -e CODECOV_TOKEN=$CODECOV_TOKEN mgmt make -C /srv/$WP_ENV/jahia2wp test-travis
